# -*- coding: utf-8 -*-
"""expense_tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVRvZsjQFK4luTeqFGSLTOr4lHcvQiL8
"""

import csv
from datetime import datetime

expenses = []

def add_expense():
    amount = float(input("Amount: "))
    category = input("Category (e.g. Food, Travel, Books): ")
    date = input("Date (YYYY-MM-DD or leave blank for today): ")
    if date.strip() == "":
        date = datetime.now().strftime("%Y-%m-%d")
    desc = input("Description: ")
    expenses.append({
        'amount': amount,
        'category': category,
        'date': date,
        'description': desc
    })
    print("Expense added!\n")

def show_expenses():
    print("\nAll Expenses:")
    for e in expenses:
        print(f"{e['date']} | {e['category']} | {e['amount']} INR | {e['description']}")
    print()

def show_totals_by_category():
    totals = {}
    for e in expenses:
        cat = e['category']
        totals[cat] = totals.get(cat, 0) + e['amount']
    print("\nExpense by Category:")
    for cat, amt in totals.items():
        print(f"{cat}: {amt} INR")
    print()

def export_to_csv():
    filename = "expenses.csv"
    with open(filename, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=['amount','category','date','description'])
        writer.writeheader()
        writer.writerows(expenses)
    print(f"All expenses exported to {filename}\n")

while True:
    print("1. Add Expense\n2. Show Expenses\n3. Totals by Category\n4. Export to CSV\n5. Exit")
    choice = input("Enter your choice: ")
    if choice == "1":
        add_expense()
    elif choice == "2":
        show_expenses()
    elif choice == "3":
        show_totals_by_category()
    elif choice == "4":
        export_to_csv()
    elif choice == "5":
        print("Goodbye!")
        break
    else:
        print("Invalid choice. Try again.\n")